### ISSUE TITLE
Support for dynamic mesh to bone binding?

### ISSUE THREAD

**Issue by kevzettler** [chinedufn/skeletal-animation-system#1]
@chinedufn I'm really excited about your work here. I've been hacking on a WebGL game for some time and I'm not happy with any of the full featured engines I have tried. The Blender -> WebGL pipeline is unstable, borderline unusable in other engines. I think skeletal animation is a critical missing piece of the stack-gl ecosystem.

 Can I manually create a mesh elsewhere, or import a separate mesh and bind it to a bone? Is that possible with this library? Like if I have a equipment like swords that I need to attach to a character. The workflow would be:

1. create armature and animations in blender with 'place holder meshes'
2. export to collada and import to WebGL environment
3. animate the armature in WebGL
4. create another mesh and bind to existing armature

  Let me know if that example makes sense.

**Comment by chinedufn** [comment]
@kevzettler First off.. apologies on my end. This skeletal animation work is pretty new and I haven't yet gotten around to examples / posts about how to do some of the common things that one would want to do. Also I'm pumped that you're excited. Feel free to keep those issues and PRs coming so that we can tighten up that pipeline!

---

So I'm assuming (correct me if I'm wrong) that you have a non-skeletally animated mesh that you want to make follow a bone. i.e. a weapon that you want in a character's right hand.

> 4. create another mesh and bind to existing armature

So, given the above, you'd do something like this:

1. Blend your keyframe poses using `skeletal-animation-system`
2. `skeletal-animation-system` [gives you a location and rotation for all of your joints that you blended](https://github.com/chinedufn/skeletal-animation-system/blob/2cf755d84ec55f03d70b19fa11bab662d76b4959/demo/upper-body.js#L6-L26)
3. Just grab the blended bone data for the bone(s) that you care about (the position and rotation) and use it to draw your static, non-animated mesh.

So in essence, `skeletal-animation-system` only cares about your armature and it's animations so it doesn't specifically handle this use case, but it does give you what you need in order to "do it yourself."

Again, apologies for the lack of a succinct place to point you to. We'll surely have to make progress over time on this front.

---

Let me know if that makes sense

**Comment by chinedufn** [comment]
Oh and additionally... this is something that I'm soon to need to do in my game so I'll definitely be making a light abstraction layer around this process soon. Feel free to do it on your own in the meantime though. Also feel free to point out anywhere that I was confusing / unclear.

**Comment by chinedufn** [comment]
@kevzettler started working on a tutorial for this. I'll post it here when I'm finished

**Comment by chinedufn** [comment]
Published a tutorial on this https://github.com/chinedufn/webgl-wield-item-tutorial
