### ISSUE TITLE
Migrate dual quat math to gl-matrix implementation 

### ISSUE THREAD

**Issue by kevzettler** [chinedufn/skeletal-animation-system#10]
This is not critical. Opening as a TODO. `gl-matrix` now has support for `quat2` operations. 

https://github.com/toji/gl-matrix/pull/231#issuecomment-383324704

I am currently using the `gl-matrix` `quat2` implementation to add post-processing dynamic transformations to `skeletal-animation-system`s output

**Comment by chinedufn** [comment]
Right now we have zero dependencies and since this code runs in the browser I'd love to at most only pull in exactly what we need if we introduced a dep.

If the `gl-matrix` implementation fairs better in our `npm run bench` (admittedly pretty sparse right now) then I'd almost advocate to instead copy paste exactly what we need.

I'd usually be against that - but in this case the math has a solid probability of never ever (or extremely rarely) changing.

---

And also I'd love to hear more about your post-processing transforms - we haven't caught up in a while!

**Comment by kevzettler** [comment]
Excellent points. forget this idea I opened the issue on reactionary hype.

**Comment by stefnotch** [comment]
@chinedufn Out of curiosity, how did the `gl-matrix` dual quaternion fare in your benchmark? If there is anything that is slower, I'd love to know more so that I can improve the `gl-matrix` dual quaternion implementation. 😄

**Comment by chinedufn** [comment]
I haven’t benchmarked anything here but if you want to give it a spin feel more than free! Although to be fair the benchmarks in this lib are extremely incomplete and extremely young.

**Comment by stefnotch** [comment]
@chinedufn Thank you for the prompt response. Is https://github.com/chinedufn/skeletal-animation-system/blob/master/src/blend-dual-quaternions.js everything that I would have to benchmark if I wanted to compare it to gl-matrix's implementation?

**Comment by chinedufn** [comment]
@stefnotch yup pretty much! Let me know if I can provide any more info - I'm more than happy to!

**Comment by stefnotch** [comment]
@chinedufn After some super quick and dirty benchmarks, it appears that the gl-matrix implementation is faster. Well, looks like I can't improve my dual quaternion implementation. (Though, once WebAssembly is more mature, there might be a version of `gl-matrix` that uses WebAssembly and is even faster.)

**Comment by chinedufn** [comment]
@stefnotch just for posterity the version in the codebase right now isn't from `gl-matrix` it's from some paper that I found that may or may not be linked to in the references (I forget...).

When Kev said `gl-matrix` he was talking about your recently merged dual quat implementation.

But sweet! Thanks a lot for looking into this friend!!!
