### ISSUE TITLE
Landing page mockup

### ISSUE THREAD

**Issue by mdkq** [chinedufn/skeletal-animation-system#6]
![mockup](https://user-images.githubusercontent.com/4454291/31683555-27e464ac-b332-11e7-84a8-81b1eec4c043.png)

Ok thoughts?

Color scheme can definitely change

could be cool to go for a more white/black/grey/reddish-pink accent scheme given that its a pretty low level tool and doesn't require the flashiness that's currently there... in fact I'm gonna experiment with that I have an idea in mind.

Not sure about single page vs multipage. I think having the demo separate is good since it could be GPU intensive for crappier computers or could break on computers that have JS disabled. But also maybe that doesn't really need to be considered given this is a JS project?

I'm thinking keep link structure as is, and getting started button auto scrolls the page to an anchor lower on the page.

**Comment by chinedufn** [comment]
Great points, my thoughts are:

I think that one of the most valuable things for a library site is to communicate how it is used. I also think that with a library like `skeletal-animation-system` an interactive visual is just valuable as API documentation. Playing with an interactive implementation helps it all click.

That being said, I'd think that the site should strive to deliver as much value as quickly as possible (without being crowded or anything of course).

Which to me suggests that one of the first things that you see should be a demo and that you shouldn't need to visit another page to get to it.

If the demo broke because JS was disabled that wouldn't prevent anything else from working so that sounds like a separate problem.

And with regards to the GPU intensive, we have complete control over the demo so we can control how GPU intensive the demo is or isn't. Making this point also feel like a separate convo to me.

So yeah overall I think that it's important to as soon as possible have something that you can interact with to get a real sense of the value of the lib, which makes me think that embedded-inside-of-same-page is a little better than different page. Maybe like a 600 x 600 canvas or something...

---

Just my thoughts though! I'll defer to you here since whatever you decide on is still many times better than what we have now!

**Comment by chinedufn** [comment]
> could be cool to go for a more white/black/grey/reddish-pink accent scheme given that its a pretty low level tool and doesn't require the flashiness that's currently there... in fact I'm gonna experiment with that I have an idea in mind.

Totally agree with you and excited for what you come up with
